### ISSUE TITLE
how to install forge

### ISSUE THREAD

**Issue by pizzahendygamin** [Asyfero/minecraftportable#3]
i changed the path c: to e:/some other folder/.minecraft and it still not installed

**Comment by Asyfero** [comment]
This is strange. Normally forge will be installed in the .minecraft folder, where forge is installed ?

**Comment by pizzahendygamin** [comment]
> This is strange. Normally forge will be installed in the .minecraft folder, where forge is installed ?

idk but can u show me a video tuto or say me how to install( what did i need to change)

**Comment by Asyfero** [comment]
On the forge installer point the .minecraft that is in the folder.
